apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: homework2
spec:
  containers:
    - name: web
      image: arsenalzz/education-homework:web-hw2
      volumeMounts:
        - name: app
          mountPath: /app

  initContainers:
    - name: init-web
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app

  volumes:
    - name: app
      emptyDir: {}
